{% set python_min = '3.10' %}
{% set name = "orix" %}
{% set version = "0.13.3" %}

package:
  name: {{ name }}-meta
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d62f40d8139169440f4ec9666c17b5d69b4f59c0f8ce81e2fe137e2b84927807

build:
  number: 0
  noarch: python

requirements:
  host:
    - hatchling
    - python {{ python_min }}

outputs:
  - name: {{ name }}-base
    build:
      script: '{{ PYTHON }} -m pip install . -vv '
      noarch: python
    requirements:
      host:
        - hatchling
        - pip
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - dask-core
        - diffpy.structure >=3.0.2
        - h5py
        - matplotlib-base >=3.6.1
        - matplotlib-scalebar
        - numba
        - numpy
        - pooch >=0.13
        # TODO: Remove when https://github.com/pyxem/orix/issues/510 is fixed
        - pycifrw
        - scipy
        - tqdm
        - typing-extensions
      test:
        requires:
          - pip
          - pytest
          - python {{ python_min }}
        imports:
          - orix
          - orix.crystal_map
          - orix.data
          - orix.io
          - orix.measure
          - orix.plot
          - orix.projections
          - orix.quaternion
          - orix.sampling
          - orix.vector
        commands:
          - export MPLBACKEND=agg  # [unix]
          - set MPLBACKEND=agg  # [win]
          - python -m pytest --pyargs orix -k "not test_get_sample_reduced_fundamental"
          - python -m pip check
  - name: {{ name }}
    requirements:
      host:
        - hatchling
        - pip
        - python {{ python_min }}
      run:
        - {{ pin_subpackage('orix-base', exact=True) }}
        - quaternion
      test:
        requires:
          - pip
          - pytest
          - python {{ python_min }}
        imports:
          - orix
          - orix.crystal_map
          - orix.data
          - orix.io
          - orix.measure
          - orix.plot
          - orix.projections
          - orix.quaternion
          - orix.sampling
          - orix.vector
        commands:
          - export MPLBACKEND=agg  # [unix]
          - set MPLBACKEND=agg  # [win]
          - python -m pytest --pyargs orix -k "not test_get_sample_reduced_fundamental"

about:
  home: https://orix.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: |
    Python library for handling of crystal orientation mapping data
  description: |
    orix defines objects and functions for the analysis of orientations
    represented as quaternions or 3D rotation vectors accounting for crystal
    symmetry. Functionality builds primarily on NumPy and Matplotlib.
  dev_url: https://github.com/pyxem/orix
  doc_url: https://orix.readthedocs.io/en/stable

extra:
  recipe-maintainers:
    - dnjohnstone
    - pc494
    - hakonanes
    - harripj
