{% set name = "orix" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 453b2937cbb74e8e74fc5a06567e3a9e81289ade10abcf07b6971af95dc62a23

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - numpy >=1.10
    - scipy >=0.15
    - matplotlib-base >=3.3.0
    - tqdm
    - diffpy.structure >=3.0.0
    - h5py

test:
  requires:
    - pytest
  imports:
    - orix
    - orix.base
    - orix.io
    - orix.plot
    - orix.quaternion
    - orix.scalar
    - orix.vector
  commands:
    - pytest --pyargs orix

about:
  home: https://github.com/pyxem/orix
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for diffraction simulations
  doc_url: https://pyxem.github.io/orix

extra:
  recipe-maintainers:
    - dnjohnstone
    - pc494
