{% set name = "orix" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1196d9923d77f6d878fd9142d05514e135844ea6ee4b4dc426e28f97dabd7d26

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - dask-core
    - diffpy.structure >=3.0.2
    - h5py
    - matplotlib-base >=3.5
    - matplotlib-scalebar
    - numba
    - numpy
    - pooch >=0.13
    - quaternion
    - scipy
    - tqdm

test:
  requires:
    - pip
    - pytest
  imports:
    - orix
    - orix.base
    - orix.crystal_map
    - orix.data
    - orix.io
    - orix.measure
    - orix.plot
    - orix.projections
    - orix.quaternion
    - orix.sampling
    - orix.vector
  commands:
    - pip check
    - export MPLBACKEND=agg  # [unix]
    - set MPLBACKEND=agg  # [win]
    - pytest --pyargs orix

about:
  home: https://orix.readthedocs.io
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: |
    Python library for handling of crystal orientation mapping data
  description: |
    orix defines objects and functions for the analysis of orientations
    represented as quaternions or 3D rotation vectors accounting for crystal
    symmetry. Functionality builds primarily on NumPy and Matplotlib.
  dev_url: https://github.com/pyxem/orix
  doc_url: https://orix.readthedocs.io/en/stable

extra:
  recipe-maintainers:
    - dnjohnstone
    - pc494
    - hakonanes
    - harripj
