{% set name = "orix" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8d365e9c37c35582c9f513dc559ee58b81cc70f7ffd3eedb991eca93cd9ad11a

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - ipython
    - scipy >=0.15
    - numpy >=1.10
    - tqdm
    - matplotlib >=3.1.1

test:
  requires:
    - pytest
  imports:
    - orix
    - orix.base
    - orix.io
    - orix.plot
    - orix.quaternion
    - orix.scalar
    - orix.vector
  commands:
    - pytest --pyargs orix

about:
  home: https://github.com/pyxem/orix
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for diffraction simulations
  doc_url: https://pyxem.github.io/orix

extra:
  recipe-maintainers:
    - dnjohnstone
    - pc494
