{% set name = "orix" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc61cd1491da1c2930c58567a5045284f0d5162e7958e687c41adeb29d58b1fb

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - numpy >=1.10
    - scipy >=0.15
    - matplotlib-base >=3.3.0
    - tqdm
    - diffpy.structure >=3.0.0
    - h5py
    - matplotlib-scalebar
test:
  requires:
    - pytest
  imports:
    - orix
    - orix.base
    - orix.io
    - orix.plot
    - orix.quaternion
    - orix.scalar
    - orix.vector
    - orix.crystal_map
    - orix.sampling
  commands:
    - pytest --pyargs orix

about:
  home: https://github.com/pyxem/orix
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for diffraction simulations
  doc_url: https://orix.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - dnjohnstone
    - pc494
    - hakonanes
