{% set name = "orix" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a576847b6ab091ca15eb39af7c12b2a5457101f2399c111f9ad65e1df09f39fc

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - dask
    - diffpy.structure >=3
    - h5py
    - matplotlib-base >=3.3
    - matplotlib-scalebar
    - numba
    - numpy
    - quaternion
    - scipy
    - tqdm
test:
  requires:
    - pytest
  imports:
    - orix
    - orix.base
    - orix.crystal_map
    - orix.io
    - orix.plot
    - orix.projections
    - orix.quaternion
    - orix.sampling
    - orix.scalar
    - orix.vector
  commands:
    - pytest --pyargs orix

about:
  home: https://github.com/pyxem/orix
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for handling of crystal orientation mapping data
  doc_url: https://orix.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - dnjohnstone
    - pc494
    - hakonanes
    - harripj
