travis:
  secure:
    BINSTAR_TOKEN: y11Ca4bD5DwzFR1KxXUQE9xz2ZpES+xDTFUeiXYsCJOPD3Wj1lGgYWFSDt2vdz8eIB2mAk5of4t1aXhoyofliyWP95SexdbWFkxrhDCDRh1c7ky8lC571vwy+kN0rBikHy4yrcDQIXFiwLgV3TY47GJcrN0BQmZv0gvC9B+eeZ8rfqEjkvwdYvIIjYlODR3soaRsNkEHiUbCw+7pCTsx7fp1Ell37KNPV993pmkfs9OdsjLIhOMBwrKU9beXqMHWzij+riOaQ8+/f4mKis3rYVYjzlG2VwtjKEW5u4YocZsCq3yKod31Xp0s/mX1ZqDm6hiGt8v2kB3Vabkk7uXtmeeqbfSjmy7am6k0np4kLkP/VxW+FU56/bFh11uvQ4CZffe+YQFBnw9uT6r0LSCxIkzRneBd9aaNKAwaYbLKOsWBET+xWSx9No6AGCfRRTOukunr0G9ytvtbRXBJUA4WwBsja28vq4DJCJQ3rfKqHu0InbXqG+jxdKkZpGoW/pgph5ckSnrmT3vXD5HEu4VoDlMmEdD0kojQ8GKlsdQYYrntQ9Hof7PfMpMYb2CYcZmLD7VH0b4vF77xewfoLsvcSurh4+LNcoPSX1kclDsdT2rR9sYUCWji5hCXRDMg7AJ6QNVH7UnKMsGkVyD/90q6hN3WBkatZqYOrPkQRGxie8o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
